ClusterLabs/fence-agents

fence/agents/scsi/fence_scsi.py
Lack of a monitor action causes stonithd to fail to start fence_scsi-based devices.  This adds support for that action in which it checks if the external commands we rely on can all be executed.
=> fence_scsi: Add support for monitor action

fence/agents/scsi/fence_scsi.py
As-is, get_status will return on if any device is on, with the result being that the library will choose to not attempt to unfence devices during an "on" action even if some devices need it.  This can be seen by adding a new device to the list and running "on", which will simply display "Success: Already ON".  We should return off if any device is off.
=> fence_scsi: status should return off if any device is off

fence/agents/rhevm/fence_rhevm.py
Hi,
Please consider pulling these fixes for the fence_rhevm agent.
Commit 03eee86 adds the Filter header to the curl command. Without this the user used to connect to oVirt/RHEV-M needs more privileges than the UserRole role. With the filter header set, the UserRole permissions are sufficient to make the fence agent work.
Commit d19bb9b fills in the status of the outlets to prevent a crash on the monitor action. This error only occurs when the list of vm's returned is non-empty (when a user with UserRole role is used).
Regards,
Rik
=> fence_rhevm fixes

fence/agents/virsh/fence_virsh.py
Escape EXPECT string to prevent nroff error "warning: can't find special
character `EXPECT\'`"
Signed-off-by: Adrian Vondendriesch <adrian.vondendriesch@credativ.de>
=> fence_virsh: escape "EXPECT" string.

fence/agents/rcd_serial/Makefile.am, fence/agents/rcd_serial/fence_rcd_serial.py
New python based delayed serial fence agent to replace the [legacy rcd_serial plugin](http://www.scl.co.uk/rcd_serial/rcd_serial.c)
- Redhat bug for missing agent: https://bugzilla.redhat.com/show_bug.cgi?id=1240868
- Original plugin: http://www.scl.co.uk/rcd_serial/README.rcd_serial
- Info about the hardware (and legacy plugin): https://smcleod.net/rcd-stonith/
Thank you to @danni & @marxsk
=> New / re-write of the rcd_serial fence agent

fence/agents/pve/fence_pve.py
SSL encrypted communication, so we set it as
default. As pve generates a self signed certificate we set
insecure ssl as default option. A unencrypted connection is rejected
by the PVE proxy so it isn't needed as an option.
Also a typo (opts instead of options) was corrected.
=> Default to SSL to comply with pve and fix typo

fence/agents/scsi/fence_scsi.py
Currently the agent will reset prior to several areas where it runs
sg_persist, to clear out any "Unit Attention" conditions that could
otherwise cause the sg_persist command to report failures.  However
several paths remain that could fail if a "Unit Attention" condition
exist, so we should reset before any use of sg_persist.
=> fence_scsi: Reset device prior to all uses of sg_persist

fence/agents/scsi/fence_scsi.py
The existing implementation of fence_scsi_check returns an error if any
device is no longer registered properly, and this error return causes
watchdog to use its custom procedure to reboot the host.  This procedure
is prone to blocking, especially when GFS2 file systems are mounted or
multipath devices are configured to queue indefinitely, so having the
check be able to hard-reboot the host instead of returning a failure
gives a means for avoiding these blockages.
=> fence_scsi: Offer hard-reboot option for fence_scsi_check script

fence/agents/docker/fence_docker.py
When setting of Docker is necessary, a message of Docker is displayed by
on commands.
However, fence_docker does not display it.
This patch displays a result when "Cannot parse json" error happened.
For example, an error(Cannot parse json) happens without setting the next option when operator execute on command.
```
/etc/sysconfig/docker-storage
DOCKER_STORAGE_OPTIONS="--storage-opt dm.no_warn_on_loop_devices=true"
```
[root@centos-master ~]# fence_docker -o on -a localhost -u 4243 -n test2
Cannot parse json
Success: Powered ON
The Docker command outputs the next message, but current fence_docker does not display it.
```
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to …
```
=> Low:The error output when operator failed in the practice of the command.

fence/agents/compute/fence_compute.py
This requires the [corresponding fix in `NovaCompute` and `NovaEvacuate`](https://review.openstack.org/#/c/247048/).
=> fix 'evacute' typo

fence/agents/ipdu/fence_ipdu.py
FENCEAGENTSLIBDIR was hardcoded to "/usr/share/fence".
=> fence_ipdu: fix hardcoded FENCEAGENTSLIBDIR.

fence/agents/zvm/fence_zvm.c
This makes fence_zvm --help conform with the other fence agents
behavior.
=> Print fence_zvm --help to stdout and exit with status 0

fence/agents/pve/fence_pve.py
More info to problem [1], this fixes the problem and allows to use dedicated user only with "VM.PowerMgmt" permission.
https://forum.proxmox.com/threads/right-permissions-to-stop-vm-with-fence_pve.26618/#post-133621
=> this fix allows to use dedicated user for fencing, not only root@pam

fence/agents/autodetect/fencing.py, fence/agents/ipmilan/fence_ipmilan.py, fence/agents/lib/fencing.py.py
Currently run_command special cases the logging of commands with ipmitool and removes everything
between the flat -P and -p. Instead of special casing commands with ipmitool allow the caller to
provide the command to log so that the command can do any necessary scrubbing of the message to be
logged.
=> fencing: Specify command to be logged by run_command

configure.ac, fence/agents/ironic/fence_ironic.py, make/fencebuild.mk, tests/data/metadata/fence_ironic.xml
Introduce a fence agent that plugs into OpenStack's Ironic (Bare Metal
as a service) service.
Testing recap:
1) With ironic services up and running
1.1) Status
$ fence_ironic -a $OS_AUTH_URL -T admin -l admin -p $OS_PASSWORD -o status -n 2b40a642-3d7b-4a43-b6a2-57a3967ebb1c
Status: ON
1.2) Power off
$ fence_ironic -a $OS_AUTH_URL -T admin -l admin -p $OS_PASSWORD -o off -n 2b40a642-3d7b-4a43-b6a2-57a3967ebb1c
Success: Powered OFF  // Machine confirmed to be off
1.3) Power on
$ fence_ironic -a $OS_AUTH_URL -T admin -l admin -p $OS_PASSWORD -o on -n 2b40a642-3d7b-4a43-b6a2-57a3967ebb1c
Success: Powered ON
1.4) Power on (when already powered on)
fence_ironic -a $OS_AUTH_URL -T admin -l admin -p $OS_PASSWORD -o on -n 2b40a642-3d7b-4a43-b6a2-57a3967ebb1c
Success: Already ON
2) With ironic …
=> Ironic fence agent

fence/agents/powerman/fence_powerman.py
References to dictionaries device_opt[], options[] and all_opt[]
sometimes used key "powerman_path" and other times "powerman-path",
resulting in references to keys that did not exist.
This resulted in total failure of the fence agent.
This commit makes the key used consistent.
=> fence_powerman: fix typo in option powerman-path

fence/agents/cisco_ucs/fence_cisco_ucs.py, fence/agents/docker/fence_docker.py, fence/agents/pve/fence_pve.py, fence/agents/rhevm/fence_rhevm.py
Introduced in Python 3 compatibility PR.
.decode() is necessary to be compatible with Python 3.
=> pycurl agents: fix StringIO issues

fence/agents/ipmilan/fence_ipmilan.py, fence/agents/lib/fencing.py.py, tests/data/metadata/fence_idrac.xml, tests/data/metadata/fence_ilo3.xml, tests/data/metadata/fence_ilo4.xml, tests/data/metadata/fence_imm.xml, tests/data/metadata/fence_ipmilan.xml
Adds --target option to support ipmitool's -t option.
=> fence_ipmilan: add target support

fence/agents/rhevm/fence_rhevm.py, tests/data/metadata/fence_rhevm.xml
Version on 4 of the oVirt engine will support two versions of the API:
version 3, which will be backwards compatible with older versions of the
engine, and version 4, which won't be compatible. The default used by the
server will be version 4, but clients can explicitly request a version
of the API using the "Version" header or the "/v3" URL prefix. The
header is the preferred mechanism because it is just ignored by older
versions of the server. This patch modifies the oVirt fence agent so
that the path and version of the API are configuratble, and so that
their default values work correctly with version 3 compatibility mode of
the API.
Signed-off-by: Juan Hernandez juan.hernandez@redhat.com
=> Explicitly use version 3 of the oVirt API

fence/agents/cisco_ucs/fence_cisco_ucs.py, fence/agents/docker/fence_docker.py, fence/agents/pve/fence_pve.py, fence/agents/rhevm/fence_rhevm.py
The 'fence_rhevm' agent uses pycurl to interact with the oVirt API, and
it builds the URLs using string concatenation. For example, to build the
URL used to start a virtual machine it does the following:
url = "vms/" + options["id"] + "/" + action
This 'id' is extracted from the XML returned by the server, which may be
a plain 'str' or an 'unicode' object, depending on the version of pycurl
used. If it is an unicode object then resulting string will also be an
unicode object. When this unicode object is passed to pycurl it fails,
with the following traceback:
Traceback (most recent call last):
...
File "/usr/sbin/fence_rhevm", line 106, in send_command
conn.setopt(pycurl.URL, url)
TypeError: invalid arguments to setopt
The same happens with other agents. To avoid that this patch changes …
=> Convert URLs passed to pycurl to ASCII

fence/agents/pve/fence_pve.py
This fixes a invalid API call to Pacemaker's stonith-ng.
=> Workaround for invalid Pacemaker API call

fence/agents/lib/fencing.py.py, fence/agents/lib/fencing_snmp.py.py, fence/agents/vmware/fence_vmware.py
Fix encoding issues with pexpect for Python 3.6 (reported in https://github.com/ClusterLabs/fence-agents/issues/132).
Thanks to @feldsam for reporting it.
I've also tested that agents using the subprocess method arent having the same issue.
=> Fix encoding for pexpect with Python 3.6

fence/agents/ifmib/README, make/release.mk
* reflect the project is also set to generate bzip2 tarball
- this change should have been part of d95ee95
* ensure checksum file generated even w/o signing
* allow full-fledged release delivery testing incl. signing
- these changes should have been part of a8a1d93
Signed-off-by: Jan Pokorný <jpokorny@redhat.com>
=> build: release.mk: further alignment with fellow projects (+ fix ifmib README typos)

.travis.yml, configure.ac, doc/COPYRIGHT, fence/agents/heuristics_ping/fence_heuristics_ping.py, fence/agents/lib/fencing.py.py, make/fencebuild.mk, tests/data/metadata/fence_heuristics_ping.xml
Not really a fencing agent by itself!
Put on the same fencing level with the actual fencing agent for
your node to make actual fencing depend on the result of (own)
connectivity determinded using ping heuristics.
resolves: rhbz#1476401
Tried to make that look as much as other fencing agents as possible
while making as much use of the fencing-library as possible.
This got a little hacky as the whole thing is quite a bit different from
the other fencing agents.
Changes to the fencing-library are minimal and shouldn't alter the
interface for existing fencing agents.
=> fence_heuristics_ping: add fencing agent for conditional fencing

fence/agents/Makefile.am, fence/agents/heuristics_ping/fence_heuristics_ping.py, tests/data/metadata/fence_heuristics_ping.xml
Without ping_targets given the agent will fail so unintentional usage as kind of a 'dummy'-fence-agent should happen less easily.
=> Fix: fence_heuristics_ping: make fence-agent fail without params

fence/agents/zvm/fence_zvm.c
Include stdint.h now that uintptr_t has been moved there according to C99 standard in libc.
=> fence_zvm: fix "uintptr_t" undeclared

fence/agents/lib/fencing.py.py
When logging to STDERR (i.e. when `--quiet` is not specified), or when logging to a debug file via `--debug-file`, include timestamps so that exact timings of fencing actions can be correlated with events logged elsewhere.
=> fencing: include timestamps when logging to STDERR and debug file

fence/agents/compute/fence_compute.py
With 549fee1c18cfb31881c9126ae46a4bd9b20b4716 ("compute: Add support for
keystone v3 authentication") we renamed the versions variable to
nova_versions. Let's make sure we use that when logging so there are
no python exceptions triggered.
=> Log the proper nova_versions variable

fence/agents/ilo_ssh/fence_ilo_ssh.py
The "hard" keyword needs to be after "/system1":
- http://systemmanager.ru/c02063194.en/116744.htm
- http://myexperienceswithunix.blogspot.in/2016/06/reset-hp-proliant-blade-server-from-ilo.html
- https://community.hpe.com/t5/Remote-Lights-Out-Mgmt-iLO-2-iLO/iLO-feature-to-reboot-the-server/td-p/3619880
- https://community.saas.hpe.com/t5/Remote-Lights-Out-Mgmt-iLO-2-iLO/iLO-feature-to-reboot-the-server/td-p/902189
=> fence_ilo_ssh: fix hard reset

fence/agents/heuristics_ping/fence_heuristics_ping.py
Traceback (most recent call last):
File "heuristics_ping/fence_heuristics_ping", line 198, in <module>
main()
File "heuristics_ping/fence_heuristics_ping", line 191, in main
sync_set_power_fn = ping_test)
File "lib/fencing.py", line 904, in fence_action
if reboot_cycle_fn(connection, options):
File "heuristics_ping/fence_heuristics_ping", line 75, in ping_test
searchres = packet_count.search(line)
TypeError: cannot use a string pattern on a bytes-like object
=> heuristics_ping: fix for python3 TypeError

fence/agents/pve/fence_pve.py, tests/data/metadata/fence_pve.xml
Hello,
By default fence_pve only allow to fence a qemu VM. This PR add a new option `--vmtype` to choose between qemu (default for compatibility) or lxc.
Regards,
=> fence_pve : choose vm type either lxc or qemu

fence/agents/gce/fence_gce.py, tests/data/metadata/fence_gce.xml
Hello
The zone & project parameters are required by the Google API :
```
>>> conn.instances().list().execute()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 716, in method
raise TypeError('Missing required parameter "%s"' % name)
TypeError: Missing required parameter "project"
>>> conn.instances().list(project="myproject").execute()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 716, in method
raise TypeError('Missing required parameter "%s"' % name)
TypeError: Missing required parameter "zone"
```
=> fence_gce : zone & project parameters are mandatory

fence/agents/docker/fence_docker.py
Hi All,
Pacemaker can not handle slashes in the list when running STONITH.
[root@rh74-test ~]# fence_docker -o list -a 127.0.0.1 -u 4243 --api-version 1.12
18e51ee177a941fe4b8b1b16239cf9d8163c5a697d5c7816aba7fde5ba114fae,/docker-remote
For this reason, a parse error occurs.
(As a result, Pacemaker fails in STONITH using fence_docker.)
Eliminate the leading slash of the container name from the result of the list.
[root@rh74-test ~]# fence_docker -o list -a 127.0.0.1 -u 4243 --api-version 1.12
18e51ee177a941fe4b8b1b16239cf9d8163c5a697d5c7816aba7fde5ba114fae,docker-remote
- In consideration of the future change of docker, I skipped only when the slash is at the beginning.
Best Regards,
Hideo Yamauchi.
=> Mid: fence_docker: Exclude slashes from the list.

fence/agents/scsi/fence_scsi.py
Changes `corosync-cmapctl nodelist.` to `corosync-cmapctl nodelist`.
Existing version works fine in my testing, so this is a simple typo
cleanup.
=> Low: fence_scsi: Remove period from cmd string

agents/scsi/fence_scsi.py
Hello
This PR adds the `re.MULTILINE` flag when matching the devices that needs to be written to `/var/run/cluster/fence_scsi.dev`.
https://github.com/ClusterLabs/fence-agents/blob/fe67112688266960d2ff4aac237477fd711be659/agents/scsi/fence_scsi.py#L237
Currently when there is more than one device already in `/var/run/cluster/fence_scsi.dev` file, then the above condition will match only the first device. If there are multiple devices for `fence_scsi` then they will get duplicated over time and file content will start look like below.
~~~
/dev/sdb
/dev/sdc
/dev/sdc
/dev/sdd
~~~
Above is result of:
- configuring `fence_scsi` with `/dev/sdb` and `/dev/sdc`, 
- then changing it to `/dev/sdb`,`/dev/sdc` and `/dev/sdd`. 
Below is example how the output will look after applying this PR (no …
=> fence_scsi: don't duplicate entries in /var/run/cluster/fence_scsi.dev

agents/scsi/fence_scsi.py
File "/usr/sbin/fence_scsi", line 184, in get_cluster_id
return hashlib.md5(match.group(1)).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
=> fence_scsi: fix python3 encoding error #206

agents/gce/fence_gce.py, tests/data/metadata/fence_gce.xml
The following changes were made provide some of the features supported by the following script:  https://storage.googleapis.com/sapdeploy/pacemaker-gcp/gcpstonith
fence_gce: add support for stackdriver logging
Add --logging option to enable sending logs to google stackdriver
fence_gce: set project and zone as not required
Try to retrieve the GCE project if the script is being executed inside a
GCE machine if --project is not provided.
Try to retrieve the zone automatically from GCE if --zone is not
provided.
=> fence_gce: logging and non required parameters

agents/kdump/fence_kdump.c, agents/kdump/fence_kdump_send.c
fence-agents-4.2.1/agents/kdump/fence_kdump.c:354: buffer_size_warning: Calling strncpy with a maximum size argument of 256 bytes on destination array "node->name" of size 256 bytes might leave the destination string unterminated.
fence-agents-4.2.1/agents/kdump/fence_kdump_send.c:119: buffer_size_warning: Calling strncpy with a maximum size argument of 256 bytes on destination array "node->name" of size 256 bytes might leave the destination string unterminated.
=> fence_kdump: fix strncpy issue

agents/rhevm/fence_rhevm.py, tests/data/metadata/fence_rhevm.xml
The help for the fence_rhevm -n (--plug) parameter is incorrect.
The current help is :
-n, --plug=[id]                Physical plug number on device, UUID or
identification of machine
should be
-n, --plug=[name]		The VM name in RHV
The fence_rhevm using the VM name passed in order to get the UUID of
that VM such that the VM can be stopped/started user REST API
<url>/vms/<vm uuid>/stop or <url>/vms/<vm uuid>/start
Issue : https://github.com/ClusterLabs/fence-agents/issues/224
Signed-off-by: emesika <emesika@redhat.com>
=> The help for the fence_rhevm -n (--plug) parameter is incorrect.

agents/rcd_serial/fence_rcd_serial.py, tests/data/metadata/fence_rcd_serial.xml
* Correct vendor URL to https://github.com/sammcj/fence_rcd_serial
* Update RHEL/CentOS version currently agent currently tested with
* Update Copyright date
For more information on this provider, see: https://smcleod.net/tech/2016/07/04/update-rcd-stonith-design.html
=> Update fence_rcd_serial to correct vendor URL

agents/rhevm/fence_rhevm.py, lib/fencing.py.py
fence_rhevm uses REST API to call RHV
In fence_rhevm , the plug parameter is actually the VN name and is used
in order to construct a REST API search request to get the VM UUID from
RHV by the VM name.
In case that the call fails an unrelated error is displayed
"Failed: Unable to obtain correct plug status or plug is not available"
Code should be changed to output a clear error in case that the REST API fail
Issue : #225
Signed-off-by: emesika emesika@redhat.com
=> fence-rhevm: improve error reporting.

agents/scsi/fence_scsi.py
The last four digits of the SCSI key will be zero padded digit between 0000-0009.
=> fence_scsi: fix incorrect SCSI key when node ID is 10 or higher

agents/rhevm/fence_rhevm.py
Starting from RHV/Ovirt 4.2 we saw issues with the agent(unable to fence) after switching to UTF-8 all worked again.
=> fence_rhevm: Changed Encoding to UTF-8

lib/fencing.py.py
- Remove quotes around stdin parameters for consistency with CLI
parameters and to be able to quote number and time parameters
=> fencing: improve stdin parse function

agents/pve/fence_pve.py, tests/data/metadata/fence_pve.xml
Restarting VMs by sending poweroff and poweron commands is slow and unreliable; machines may hang or time out during shutdown.
A better option, at least for qemu VMs, is to send a "reset" command. This immediately reboots the VM, just like pressing the reset button on a physical server.
This patch implements the required changes. The new reboot code is activated by providing the option method=cycle.
=> fence_pve: add support for sending reset command to qemu machines

agents/ipmilan/fence_ipmilan.py, tests/data/metadata/fence_idrac.xml, tests/data/metadata/fence_ilo3.xml, tests/data/metadata/fence_ilo4.xml, tests/data/metadata/fence_ilo5.xml, tests/data/metadata/fence_imm.xml, tests/data/metadata/fence_ipmilan.xml
The default ipmitool timeout in some versions is
extremely short (on the order of 1s), and in
newer versions it is 2s by default.
This commit adds an option to configure the
timeout, and sets the default timeout to 2s.
Signed-off-by: Kristoffer Gronlund <kgronlund@suse.com>
=> fence_ipmilan: Add ipmitool timeout option

agents/azure_arm/fence_azure_arm.py, tests/data/metadata/fence_azure_arm.xml
The "skip_shutdown" parameter is ignored in older Azure SDK, so there's
no need for a fallback option.
=> fence_azure_arm: use skip_shutdown feature when available

agents/rhevm/fence_rhevm.py
Tested with UTF-8 encoded comment in result, which caused this issue,
and added to command and url in case they are in UTF-8 decoded state.
=> fence_rhevm: fix debug encoding issues

agents/raritan/fence_raritan.py
fspawn defaults to utf8 encoding, which does not work with the raritan
telnet connection (UnicodeDecodeError)
=> Changed encoding for the raritan telnet connection to latin1

agents/vmware_rest/fence_vmware_rest.py
If any VMs in the vCenter are suspended, you get a KeyError because that state is not expected.  This breaks list and monitor actions.
=> Fixed issue with SUSPENDED VMs

agents/kdump/fence_kdump.c, lib/fencing.py.py, tests/data/metadata/fence_kdump.xml, tests/data/metadata/fence_vmware.xml
This is done to improve readability of text when reading it from output of '-o metadata' like 'pcs' does for only 2 agents where these formatting string were found.
~~~
$ sed -i "s:\\\\\\\\f[IPRB]:':g" ./agents/kdump/fence_kdump.c
$ sed -i "s:\\\\\\\\f[IPRB]:':g" ./agents/vmware/fence_vmware.py
~~~
Text that was defining command line arguments has no quotes, just removed formatting strings.
If anything else needs changing in here feel free to let me know. This should not affect functionality. This targets only documentation of the `fence_kdump` and `fence_vmware` fence agents.
=> replace hard-to-read formatting marks with quotes where appropriate

agents/compute/fence_compute.py, agents/evacuate/fence_evacuate.py, tests/data/metadata/fence_compute.xml, tests/data/metadata/fence_evacuate.xml
The region_name attribute for fence_compute and fence_evacuate is not a boolean
and should expect a string argument.
=> fence_compute/fence_evacuate: fix argument parsing for region_name

agents/compute/fence_compute.py
In OpenStack Train we first observed that IHA was not working via
https://bugzilla.redhat.com/show_bug.cgi?id=1760213
The reason for this is that nova has made the disabling of the compute
service depend on the compute node being up via:
https://review.opendev.org/#/c/654596/
By first calling force-down, the subsequence service-disable API
call won't wait for the reachability of the compute node any
longer and the whole operation has the same outcome.
Tested this on an OSP Train environment and we correctly
got Instance HA working again and we observed the VMs being
restarted on the available compute nodes.
While doing this change we also remove the code that
tries to fallback in case the force-down API is not available in
nova. We do this to simplify the code a bit, and we can do so …
=> Invert the force-down/service disable order

agents/rhevm/fence_rhevm.py, tests/data/metadata/fence_rhevm.xml
We are using fence_rhevm many places but it was annoyingly spamming the RHV manager event logs with a new login every time the agent run status or any other actions. Reuse cookie was handy in case another action happened during the same session.
The change introduce a new option, --cookie-file. It should be full path where the cookie file should be created. By default the name is generated from the IP+username and the file created under /tmp.
This way the agent will store the cookie and use the same session until it's available. In case of manager restart new session will be opened.
In case the cookie file is stored on clustered filesystem the session will be kept in case of cluster node restarts or resource move.
=> fence_rhevm: added cookie file management

agents/vbox/fence_vbox.py, agents/virsh/fence_virsh.py, tests/data/metadata/fence_vbox.xml, tests/data/metadata/fence_virsh.xml
The `status` action (and any other status-based actions, like `off`,
which checks the status beforehand) was broken - it always
returned OFF for all the virtual nodes, even for the running ones:
``` 
$ fence_vbox -o list-status -a 10.0.2.2 -l 520414 --host-os=macos -k .ssh/id_rsa
centos_1905.1_pod-c1,0872858e-132e-44bc-89fe-23f7608cadb0,off
centos_1905.1_cmu,f9172ad8-0700-4c65-9aac-304f60175f44,off
centos-7-1-1.x86_64_1572001960195_51877,d8e19439-3cc7-43fc-8fd4-16b8c673f8f4,off
centos_1905.1_pod-c2,5eef6fe9-de25-4891-8326-d440a633d6a9,off
$ fence_vbox -o status -a 10.0.2.2 -l 520414 --host-os=macos -k .ssh/id_rsa --plug centos_1905.1_pod-c2
Status: OFF 
$ fence_vbox -o off -a 10.0.2.2 -l 520414 --host-os=macos -k .ssh/id_rsa --plug centos_1905.1_pod-c2
Success: Already OFF 
``` 
The logs …
=> fence_vbox/fence_virsh: fix prompt issue for status-based actions

fence-agents.spec.in
Fixes python 2 BRs from https://github.com/ClusterLabs/fence-agents/pull/305.
=> spec: fix openstack BuildRequires for distros without Python 3

agents/redfish/fence_redfish.py, agents/vmware_soap/fence_vmware_soap.py
python-requests doesnt suppress warnings anymore, so it needs to be done in urllib3: https://stackoverflow.com/questions/27981545/suppress-insecurerequestwarning-unverified-https-request-is-being-made-in-pytho/28002687#28002687
=> fence_redfish/fence_vmware_soap: suppress warnings correctly with new python-requests

configure.ac
If some autodetect agent is last in the list it will not be filtered
(no trailing space) and the build will fail.
=> configure: fix agent filtering

agents/aws/fence_aws.py, tests/data/metadata/fence_aws.xml
Hello,
This PR has the objective to improve overall fence_aws functionality aligned with customer and field feedback.
- **Fix fence Race condition**
Added a function called ```get_self_power_status()``` in which the instance executing the fence action will check its own status before fencing the other node. If the local EC2 instance's status is not "Running" it will not try to fence the other node as the local node has been already fenced. With the addition of this feature ```pcmk_delay_max``` and/or ```pcmk_delay_base``` can now be used and are encouraged to be used with fence_aws.
- **Logging Changes**
Stopped using parent "logging" from lib fencing.py and added its own local logger. The reason for this is to 1) avoid logs from being streamed to _stderr_; and 2) avoid hitting [RHBZ …
=> fence_aws: Fix fence race, logging improvement and new debug option

agents/gce/fence_gce.py
The underlying google api code cache discovery process
uses deprecated code. In order to avoid the usage of that
code and the related warning messages the cache usage is
disabled
=> fence_gce: Disable google api cache discovery

agents/vmware_rest/fence_vmware_rest.py
If an exception occurs, simply raise it. pycurl's perform() method can
generate a pycurl.error object, which does not support indexing and
attempting to do so will generate an exception that hides the original
exception.
Also, don't assume that the remote will return a JSON formatted response.
If it doesn't, a exception will occur accessing result which will not
raise the intended exception.
=> fence_vmware_rest: improve exception handling in send_command()

agents/vmware_vcloud/fence_vmware_vcloud.py
If an exception occurs, simply raise it. pycurl's perform() method
can generate a pycurl.error object, which does not support indexing and
attempting to do so will generate an exception that hides the original
exception.
Also, don't assume that the remote will return a JSON formatted response.
If it doesn't, an exception will occur accessing result, which will not
raise the intended exception.
=> fence_vmware_cloud: improve exception handling in send_command()

Makefile.am
manpages could happen before fencing.py was generated
=> build: add directory dependencies to avoid edge-case where generating

agents/openstack/fence_openstack.py, configure.ac
Remove build dependency and always allow printing of metadata
similar to fence_compute and fence_evacuate.
=> fence_openstack: import novaclient and keystone only when needed

agents/aws/fence_aws.py, tests/data/metadata/fence_aws.xml
ConnectionError is reported in list-action when using a role and blocking HTTPS.
=> fence_aws: catch ConnectionError, suppress traceback for caught exceptions and improve boto3_debug boolean handling

fence-agents.spec.in
fence-compute depends on novaclient to work, so this commit adds
the explicit dependency to make sure the necessary rpm is
installed along the fence-agent.
=> Make sure fence-compute depends on novaclient

agents/evacuate/fence_evacuate.py
This commit extends the flavor.list() api call to fetch private
flavors that could be tagged with the 'evacuable' attribute,
essentially allowing instance-ha to be enabled on a per tenant basis.
=> [fence_evacuate] Enable evacuation of instances using private flavors

agents/lpar/fence_lpar.py
The `list-status` action prints "UNKNOWN" status for all LPARs when
`--hmc-version` is `"4"` or `"IVM"`.
Here we fix that by mapping the statuses returned by the HMC
(e.g., "Running") to the statuses that the fencing library expects
(e.g., "on").
We also refactor `get_lpar_list` to reduce code duplication.
Resolves: RHBZ#1861926
=>  fence_lpar: Fix list-status action

agents/gce/fence_gce.py, tests/data/metadata/fence_gce.xml
Adding an additional --baremetalsolution command line argument to support GCE baremetal API changes
Enabling FENCE_GCE_URI_REPLACEMENTS environment variable for generic gogoleapi URI replacement
Adding --retries, --retrysleep, --apitimeout to fine tune the API call timeout, retries, and retry sleep
=> Adds baremetal support to GCE fence agent and API call retries

agents/crosslink/README.md, agents/crosslink/fence_crosslink.py, tests/data/metadata/fence_crosslink.xml
As suggested by Andrew we came up with this small agent
to cater for a very specific two-node use-case where a crosscable
connects the two nodes and there is no external PDU fencing
available (aka only the integrated BMC is usable).
With this agent we can make the assumption that if the crosscable
is not available the other node has been powered off.
It is meant to be used with the normal BMC/IPMI fencing as a second
level. See the README.md file for more information.
Co-Authored-By: Damien Ciabrini <dciabrin@redhat.com>
=> Add a fence_crosslink agent

agents/gce/fence_gce.py, tests/data/metadata/fence_gce.xml
to avoid rejoining the cluster before the cycle action completes.
=> fence_gce: default to onoff

agents/vbox/fence_vbox.py, tests/data/metadata/fence_vbox.xml
This change disables bash history when checking vm status on host.
Useful mainly in devel installations, where fence_vbox.py fills user .bash_history with:
VBoxManage list vms
VBoxManage list runningvms
I think that there is no reason to log those commands in production environment, hence this pull request.
Tested on Centos7.8 and Virtualbox 6.1.16
=> fence_vbox: do not flood host account (history) with vboxmanage calls

agents/ipmilan/fence_ipmilan.py, fence-agents.spec.in, tests/data/metadata/fence_idrac.xml, tests/data/metadata/fence_ilo3.xml, tests/data/metadata/fence_ilo4.xml, tests/data/metadata/fence_ilo5.xml, tests/data/metadata/fence_imm.xml, tests/data/metadata/fence_ipmilanplus.xml
Lanplus (IPMI protocol version 2) is the up-to-date protocol to
connect to all recent IPMI driven BMCs.
Using fence_ipmilan without lanplus=1 will fail on these.
To get around compatibility issues (old HW might still exist),
a new fence_agent is introduced via link and basename check.
This fixes #314.
=> Add fence_ipmilanplus as fence_ipmilan wrapper always enabling lanplus

agents/gce/fence_gce.py
We just found out `python3-oauth2client-gce` is required too, in SLES 15.
=> fence_gce: update module reqs for SLES 15

.travis.yml, agents/gce/fence_gce.py, tests/data/metadata/fence_gce.xml
This change adds the necessary scope for using the fence agent on bare metal. Along with that we have added proxy flags in case the customer is using a proxy for internet access instead of a NAT gateway
=> fence_gce: Adds cloud-platform scope for bare metal API and optional proxy flags

agents/gce/fence_gce.py
oauth2client deprecated info: https://pypi.org/project/oauth2client/
=> fence_gce: support google-auth and oauthlib and fallback to deprecated libs when not available

fence-agents.spec.in
Fixes "make rpm" failing due to "ambiguous python shebang" when not
specifying PYTHON=.../python3.
=> spec: use python3 path for newer releases

agents/gce/fence_gce.py, tests/data/metadata/fence_gce.xml
Moving back to powercycle as the default method for GCE.  This is the recommended approach from Google.  Using on/off as the default will have unintended consequences on google cloud platforms.
=> Default method moved back to powercycle

agents/openstack/fence_openstack.py, lib/fencing.py.py, tests/data/metadata/fence_openstack.xml
* Remove unnecessary imports
* Change path append to macro
* Check for novaclient import separate from keystoneclient
* Ignore urllib3 warnings due to self-signed certificates
* Enable logging to syslog
* Add list and list-status functionality
* Deal with many more client exceptions
* Change from REBOOT_HARD to HARD due to API change
* Replace nova_run_command with get_power_status and set_power_status
* Added cacert option to authenticate against self-signed certificates
* Added apitimeout to pass to the client session
=> fence_openstack: Major rework of the original OpenStack agent.

agents/mpath/fence_mpath.py, tests/data/metadata/fence_mpath.xml
Added options to be able to be able to set number of retries and sleep between retries.
=> fence_mpath: watchdog retries support

agents/azure_arm/fence_azure_arm.py, lib/azure_fence.py.py
This is based on the work in #410.
It adds some code to check for the possibility to import some modules and access some attributes.
It tries to use the newer module `azure.identity / azure.core` first and falls back to `azure.common` if this fails.
This is not the approach mentioned e.g. here https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate#other-authentication-methods / https://gist.github.com/lmazuel/cc683d82ea1d7b40208de7c9fc8de59d or here https://github.com/jongio/azidext/blob/master/python/azure_identity_credential_adapter.py.
The obove approaches did not work out as they import again `azure.core.pipeline` which is only available with newer API versions.
My test systems which run this code flawlessly are:
```
sles12sp3:~ # rpm -q python-azure-mgmt …
```
=> fence_azure_arm: corrections to support Azure SDK >= 15 - including backward compatibility

agents/cdu/fence_cdu.py, fence-agents.spec.in, tests/data/metadata/fence_cdu.xml
This fence has been found in a really old Ubuntu fence-agents version
(distro precise from 2012) and was added by a separate tarball.
It has been re-worked to be compatible with latest fence-agents mainline
package, tested against a SENTRY power switch with firmware version 7.1a.
The original code has been written by Andres Rodriguez. Beside adding myself
with a recent copyright notice reflecting my changes, the original license
description on top of the sources (GPL) is untouched.
No idea why this never made it mainline, but I can confirm it convenient
and working with the HW I tested against.
Main credits for the original fence development go to:
CC: Andres Rodriguez <andres.rodriguez@canonical.com>
=> fence_cdu: new fence agent

agents/sbd/fence_sbd.py
Hi All,
This PR is a modified version of the next PR.
- https://github.com/ClusterLabs/fence-agents/pull/420
Best Regards,
Hideoo Yamauchi.
=> Mid: fence_sbd: A warning message is output when disable-timeout is enabled. 

agents/pve/fence_pve.py, tests/data/metadata/fence_pve.xml
refactor to suit original intent of internal `nodename` logic.
Change;
* `pmx-node` option is used to specify the proxmox cluster node controlling the vm
* `nodename` option indicates the "node to fence"
`fence_pve` relies on `plug` for node actions and never `nodename` - this is unchanged
Current behaviour;
If nodename is not provided to the fence agent, autodiscovery will fail during fencing activities.
* The "watch/list" behaviours would execute correctly, (due to no nodename provided for those actions).
* Status and all node-focused actions would fail due to nodename being the cluster node, not the proxmox node. ​
New behaviour;
* ​If `pmx-node` is provided to the fence agent, it will use that node
* ​if `pmx-node` is not provided to the fence agent, it will discover and set it …
=> fence_pve: Replace `nodename` with `pmx-node` in fence_pve.py (matching original intent)

agents/kdump/fence_kdump.c, tests/data/metadata/fence_kdump.xml
Based on proposal (and feedback from @oalbrigt) in Issue https://github.com/ClusterLabs/fence-agents/issues/370 I have prepared and tested following code that adds support for `fence_kdump` to accepts both 'single node' and 'comma-separated list of nodes' from which valid message is accepted. This should improve fence_kdump ability to receive message from more than single IP which is typically possible in RRP clusters or clusters with several heartbeat links between nodes. Check the https://github.com/ClusterLabs/fence-agents/issues/370 for more detailed explanations.
Code proposed in this PR changes the behaviour of `fence_kdump` when comma-separated list of node is provided to `--nodename`/`-n` attribute. Using only one node as done so far will NOT cause any change in behaviour. There …
=> fence_kdump: accept message from multiple addresses (useful for RRP clusters)

agents/kdump/options.h
https://github.com/ClusterLabs/fence-agents/issues/429
=> fence_kdump: properly support -v[X] and -vvv (and combinations)

agents/kubevirt/fence_kubevirt.py, tests/data/metadata/fence_kubevirt.xml
API_VERSION is right now hard coded to 'kubevirt.io/v1'. E.g. CNV
2.6.X still has v1alpha3. This introduce --apiversion parameter,
which defaults to 'kubevirt.io/v1', but still allows to set a
differen version if required.
=> fence_kubevirt: make apiversion a parameter

agents/ibmz/fence_ibmz.py, tests/data/metadata/fence_ibmz.xml
Add support for the "Load during activation" option for IBM Z. This
option let's a system administrator specify a load device from which the
LPAR is loaded automatically during activation.
If the fence agent is invoked with the --load-on-activate command line
argument, the API request for an explicit load operation is skipped,
ultimately relying on the configuration of the "Load during activation"
option in the activation profile.
Signed-off-by: Bjoern Walk <bwalk@linux.ibm.com>
Signed-off-by: Bodo Brand <bodo.brand1@ibm.com>
=> fence_ibmz: add option --load-on-activate

agents/openstack/fence_openstack.py, tests/data/metadata/fence_openstack.xml
allow the agent to use Base OS defaults vs forcing a specific file
to increase portability.
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>
=> fence_openstack: relax ssl cacert default

lib/Makefile.am
the main problem is that automake does not really deal well
with dependencies between subdirs when doing parallel builds
with -j.
the simplest solution is to disable parallel build for, and only for,
the top level makefile.
this will force make to first dive into lib/ and then everything.
parallel builds of agents and doc will continue to work as expected
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>
=> build: fix parallel build of lib/ vs agents/

agents/kubevirt/fence_kubevirt.py, tests/data/metadata/fence_kubevirt.xml
If --namespace is not provided to kubectl, a default one is taken from
kubeconfig context. Let fence_kubevirt behave similarly.
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
=> fence_kubevirt: take default namespace from context

agents/lpar/fence_lpar.py
and slightly re-factor code to avoid duplicate code lines.
Should be cleanup only, no functional change.
=> fence_lpar: fix missing import logging, use fail_usage

agents/apc/fence_apc.py
#475 My bad, I accidentaly removed the last pull request. Since APC/Schneider Electric released major version 7 of the firmware, this is a workaround to keep the script using the "*5s" methods. The implementation seems to still work fine, but I did not perform extensive and detailed tests. Moreover a more robust and safe control on the major version number has to be considered.
=> fence_apc.py compatibility for Firmware major release 7 workaround #475

agents/mpath/fence_mpath.py, agents/scsi/fence_scsi.py, tests/data/metadata/fence_mpath.xml, tests/data/metadata/fence_scsi.xml
Hi Oyvind,
Hi All, 
This fix fixes the issue presented in the next issue.
- https://github.com/ClusterLabs/fence-agents/issues/482
Add --suppress-errors to /etc/sysconfig/stonith to suppress the logs output when used with the watchdog service.
Best Regards,
Hideo Yamauchi.
=> Mid: fence_scsi,fence_mpath: Add suppress-errors option.

agents/ibm_powervs/fence_ibm_powervs.py, tests/data/metadata/fence_ibm_powervs.xml
- Added support for API key instead of programmatic token. Token itself is requested with API key.
- Added support for private and public API URIs (default is public)
- Added support for proxy server
- Introduced 2s delay before every API call
=> fence_ibm_powervs: add support for proxy, private API servers and get token via API key

agents/sbd/fence_sbd.py, lib/fencing.py.py, tests/data/metadata/fence_sbd.xml
basically when using 3 disks be happy with 2 answers
As run_commands - executes a couple of commands in parallel and is happy
if more than half of them do return positive - is actually generic I put it
in lib/fencing.py.py
There is a certain amount of code-duplication between run_commands and
run_command so that we could make run_command a simple wrapper.
Basic difference between run_command and run_commands, when executing a
single command, should be how stdout & stderr are collected.
With commands that do leave D state children behind subprocess.communicate
seems to be hanging till the D state child is gone. Having leftover D state children
is ugly but waiting till eternity for them to disappear is even more.
Parallel execution and kind of "quorum-decision" could be addressed in sbd
as …
=> fence_sbd: improve error handling

agents/lpar/fence_lpar.py
Without this patch we get ERROR logged with trace info when doing status-action for nodes that doesnt exist.
=> fence_lpar: only output additional error output on DEBUG level

agents/virt/common/log.c, agents/virt/fence_virtd.service.in, agents/virt/include/static_map.h, agents/virt/man/fence_virt.conf.5, agents/virt/server/Makefile.am, agents/virt/server/mcast.c, agents/virt/server/serial.c, agents/virt/server/static_map.c, agents/virt/server/tcp.c, agents/virt/server/vsock.c, fence-agents.spec.in
Tested with both libvirt and cpg backends.
Tested with mcast, tcp, vsock and serial listeners.
NOTE: the serial listener has both "serial" and "vmchannel" mode. I was able to test only "serial" mode as vmchannel requires a libvirt managed bridge for intercepting TCP connections and I don´t have that setup.
Updated man page for group based on all different setups.
Resolves: https://github.com/ClusterLabs/fence-agents/issues/515
=> Fence virtd groups

agents/amt/fence_amt.py, agents/ipmilan/fence_ipmilan.py, agents/ironic/fence_ironic.py
https://docs.python.org/3/library/pipes.html
=> fence_amt/fence_ipmilan/fence_ironic: use shlex instead of pipes when available, as pipes is deprecated and will be removed in Python 3.13

agents/scsi/fence_scsi.py
**Problem:**
ISID (Initiator Session ID) which belongs to I_T Nexus, changes for RHEL based on the session ID that's used for iSCSI connections. This means that the connection to the same device can be set up with different ISID on reconnects.
If an iSCSI client establishes a connection with a device using an ISID (say X) and registers/reserves with the device using a key, the key is associated with the I_T nexus (with ISID X). Now if a device reconnects for some reason (like client reboots), it establishes a new iSCSI connection (with ISID Y) and fence agent tries to register again. However fence_scsi looks up the reservation key for the device, sees that it matches with the key and skips sending a new registration command assuming that the key belongs to it (ignoring the ISID). …
=> fence_scsi: fix registration handling if ISID conflicts

agents/aws/fence_aws.py, tests/data/metadata/fence_aws.xml
- add --skip-race-check parameter to allow running outside of AWS network e.g. for openshift
- fixed and improved logging logic
- use --debug-file parameter for file logging
=> fence_aws: fixes to allow running outside of AWS network

agents/scsi/fence_scsi.py
In the earlier version, the shared devices can be auto-populated
using the 'c' flag in 'vgs' command output when shared VG is 
configured with clvm. With the release of lvmlockd, the shared VGs 
has 's' flag under 'Attr' section. 
So as to make the auto-detection feature working for lvmlockd, 
this update will allow the fence/unfence operation succeed 
even when the 'devices' attribute is left blank or undefined.
=> fence_scsi: Fixes for auto-detecting devices for shared VG

agents/gce/fence_gce.py, tests/data/metadata/fence_gce.xml
If earlyexit is enabled then power_cycle will exit before the execution of the power cycle on the gce instance is complete.
=> fence_gce: add earlyexit parameter to power_cycle_instance

agents/mpath/fence_mpath.py, agents/scsi/fence_scsi.py, tests/data/metadata/fence_mpath.xml, tests/data/metadata/fence_scsi.xml
Currently the devices associated with fence_scsi should be comma-separated. With this commit, fence_scsi will also work if the 'devices' are space-separated.
Additionally, this commit includes meta-data update:
1. For fence_scsi:
- The 'devices' parameter is optional if the cluster is configured with clvm/lvmlock.
- The 'devices' parameter can be comma or space-separated.
2. For fence_mpath:
- The 'devices' parameter can be comma or space-separated.
=> fence_scsi: Add support for space-separated devices and update in meta-data

fence-agents.spec.in
Both Fedora and openSUSE now recommends to use SPDX shortname format for License.
This work is 1:1 based on Fedora patch made by Antonio Torres <antorres@redhat.com> and he should get all credit.
=> spec: Migrate to SPDX license

agents/scsi/fence_scsi.py
We need a future version of Pacemaker to be able to allow degraded results, and only return in those cases, as it'll return endlessly until it hits the migration threshold if we do it with current versions.
https://github.com/ClusterLabs/fence-agents/pull/501
=> fence_scsi: fail monitor action when it's unable to change state of device

agents/scsi/fence_scsi.py
Reverts ClusterLabs/fence-agents#503
We need a future version of Pacemaker to be able to allow degraded results, and only return in those cases, as it'll return endlessly until it hits the migration threshold if we do it with current versions.
=> Revert "fence_scsi: fail monitor action when it's unable to change state of device"

README.md, agents/eaton_ssh/fence_eaton_ssh.py, configure.ac, docker/Dockerfile, docker/README.md, docker/entrypoint.sh, fence-agents.spec.in, tests/data/metadata/fence_eaton_ssh.xml
Since the Eaton SNMP fence is not feasible for the infrastructure I am responsible for, I have decided to implement this fence that will use the Eaton SSH/Serial interface.
I also took the liberty to reformat the README to 120 characters so it is easier readable when looked at in raw and to improve the Python typing experience so adding new fences is easier.
=> fence_eaton_ssh: new fence agent for Eaton ePDU G3 over SSH

lib/fencing.py.py
~~- Four error codes (EC_INVALID_PRIVILEGES, EC_STATUS_HMC, EC_FETCH_VM_UUID, and EC_BAD_ARGS) have not been used, thus they can be dismissed.~~
- Add error message for EC_GENERIC_ERROR
- Use EC_OK and return result (equals to EC_OK).
=> fencing: Add Error Message & Use EC_OK

agents/zvm/fence_zvmip.py, tests/data/metadata/fence_zvmip.xml
In RHBZ#1935641, IBM explained that the requesting user needs authorization
for more functions than what is currently documented.
They said:
"""
What we found is that you need rights from three different NICKS:
SYSTEM_MANAGEMENT, IMAGE_CHARACTERISTICS and IMAGE_OPERATIONS.
You won't be able to give a user all three NICKS.
Therefore, you have to create a new NICK with all capabilities from all
three NICKS together and then assign the new NICK to the USER
"ZCLUSTER".
Even better is to just use the needed Subset with a new NICK.
We found five commands which are used in the fencing code and on the
z/VM Log which should be enough for fencing to work.
We suggest creating following files:
File VSMWORK1 NAMELIST:
```
:nick.ZVM_FENCE
:list.
IMAGE_ACTIVATE
IMAGE_DEACTIVATE
IMAGE_STATUS_QUERY …
```
=> fence_zvmip: Update longdesc to document all required functions

agents/azure_arm/fence_azure_arm.py
Problem:
The `fence_azure_arm`  script shows the following error: 
```sh
VirtualMachinesOperations.get() takes 3 positional arguments but 4 were given
```
Explanation:
The function virtual_machines.get() has changed its signature from:
```python
def get(
self,
resource_group_name,
expand=None,
**kwargs
):
```
to:
```python
def get(
self,
resource_group_name: str,
machine_name: str,
expand: Optional[Union[str, _models.InstanceViewTypes]] = None,
**kwargs: Any
) -> _models.Machine:
```
Therefore, the number of positional arguments has been reduced to two: `resource_group_name` and `machine_name`, while the `expand` parameter has swift from a *positional argument* to a *keyword-only argument*: https://github.com/Azure/azure-sdk-for-python/pull/27590/files#diff-d5feb43fb2e32f16f624d64917b3fa78 …
=> fence_azure_arm: fix get virtual machines call

agents/ovm/fence_ovm.py, tests/data/metadata/fence_ovm.xml
This PR is in response to https://github.com/ClusterLabs/fence-agents/pull/565#discussion_r1374182284.
Replace "ssl_client_cert_file" with "ssl_client_certificate_file".
=> fence_ovm: Replace all_opt "ssl_client_cert_file" with "ssl_client_certificate_file"

agents/vmware_rest/fence_vmware_rest.py
The call https://{api_host}/api/vcenter/vm is subject to permission checks. If the delivered list is empty the user has no rights.
=> fence_vmware_rest: monitoring action is not detecting if the API user has sufficient right to manage the fence device.

agents/docker/fence_docker.py, tests/data/metadata/fence_docker.xml
With this change we extend the Docker connection options to connect via a UNIX socket. To do so we add a new command line argument --unix-socket which expects the path to the Docker socket.
Also in order for this to make sense we disable the default setting of the SSL verification.
Closes #581
Closes #582
=> fence_docker: Connect to Docker via a UNIX socket

lib/azure_fence.py.py
fence_azure: fix pinning client api versions for compatibility across different azure sdk versions
=> fence_azure: fix pinning client api versions for compatibility across different azure sdk versions

agents/ahv/fence_ahv.py, agents/nutanix_ahv/fence_nutanix_ahv.py, fence-agents.spec.in, tests/data/metadata/fence_nutanix_ahv.xml
This patch adds fence agent support for Nutanix AHV clusters. More specifically the initial support is aimed at AHV clusters that support Nutanix v4 APIs. V3 APIs are not supported.
Signed off by <amir.eibagi@nutanix.com>
=> fence_nutanix_ahv: Add fence agent support for Nutanix AHV Cluster

agents/sbd/fence_sbd.py, configure.ac, make/fencebuild.mk, tests/data/metadata/fence_sbd.xml
=> fence_sbd: get devices from SBD_DEVICE env variable if devices parameter isnt set

agents/azure_arm/fence_azure_arm.py, lib/azure_fence.py.py
Hi all,
this is a implementation to use `azure.identity` instead of `msrestazure`.
`msrestazure` is still there and will be used when `azure.identity` is not available.
Br
=> fence_azure_arm: use azure-identity instead of msrestazure, which has been deprecated

agents/compute/fence_compute.py, agents/evacuate/fence_evacuate.py
/usr/sbin/fence_compute:288: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
=> fence_compute/fence_evacuate: dont use deprecated inspect.getargspec()

agents/sbd/fence_sbd.py, tests/data/metadata/fence_sbd.xml
The parameter tells fence agent to message a "crashdump" poison pill rather than "reset/off" through sbd device.
Following the logic from https://github.com/ClusterLabs/sbd/blob/main/agent/sbd.in#L76-L79
=> fence_sbd: Add crashdump option

agents/virt/server/virt-serial.c
libxml2 removed ATTRIBUTE_UNUSED defination since 2.14: https://gitlab.gnome.org/GNOME/libxml2/-/commit/208f27f9641a59863ce1f7d4992df77f7eb0ea9d
=> [virt] fix build with libxml 2.14

agents/virt/server/Makefile.am
linking libs should be put into `LIBADD` rather than `LDFLAGS` for shared libraries, including modules. Otherwise it may cause [underlink problems](https://wiki.mageia.org/en/Underlinking_issues_in_packaging#How_to_fix) with older libtool.
Another problem is `virt` and `cpg` are actually using libuuid, but the library is not linked.
=> fence_virtd: fix linkage of server modules

agents/shelly/fence_shelly_gen2.py, fence-agents.spec.in, tests/data/metadata/fence_shelly_gen2.xml
Adds new Fence Agent for Shelly Gen 2+ Switch devices.
I wasn't 100% on `--plug` flag intent, so I pulled in `--sw-id` (from shelly api) as a new param, but if they serve the same intent, should probably be unified.
=> fence_shelly_gen2: new fence agent for Shelly Gen2+ Switches
