ClusterLabs/fence-agents

fence/agents/lpar/fence_lpar.py
fence/agents/mpath/fence_mpath.py
fence/agents/zvm/fence_zvmip.py

Without this, python is unhappy about the files

Fix bad whitespace in lpar, mpath and zvmip agents

---

fence/agents/rcd_serial/Makefile.am
fence/agents/rcd_serial/fence_rcd_serial.py
fence/agents/rcd_serial/rcd_serial_cable_diagram.svg

As per https://bugzilla.redhat.com/show_bug.cgi?id=1240868#c15
Also added serial diagram as SVG into the source which renders to:

fence_rcd_serial: update description, makefile & add circuit diagram

---

fence/agents/amt/fence_amt.py

The 'amttool' command takes the AMT_PASSWORD environment variable.
When amttool prompts for a confirmation the variable is read only
by the left side of the pipe command:
- Broken:
$ AMT_PASSWORD='foobar' echo 'y' |  /usr/bin/amttool nuc2 powerdown
401 Unauthorized at /usr/bin/amttool line 129.
- Working:
$ AMT_PASSWORD='foobar' sh -c "(echo 'y' | /usr/bin/amttool nuc2 # powerdown)"
execute: powerdown
result: pt_status: success
A longer-term fix is to remove the amttool dependency and implement the
calls directly via the python-openwsman package

Fix AMT fence agent

---

configure.ac
fence/agents/vbox/Makefile.am
fence/agents/vbox/fence_vbox.py
tests/data/metadata/fence_vbox.xml

Adds a fencing agent for virtual machines managed by VirtualBox.
Based on fence_virsh, tested with VirtualBox version 5.0.4 on
openSUSE 13.2.

fence_vbox: Add a fencing agent for VirtualBox

---

fence/agents/compute/fence_compute.py

Since Nova API version 2.11, there is now a new novaclient tool
that allows to bypass the servicegroup check and not wait for it
to catch the right host liveness. Using it as a first try and if
failing, fallbacking to the existing polling.

Set mark host down flag if possible

---

fence/agents/compute/fence_compute.py

In order to select which instances could be evacuated automatically,
the instance has to have either:
- a flavor where one extra spec key is "evacuate" with "True" as value
- an image where a metadata key is "evacuate" with "True" as value
In case one instance is neither having a flavor or an image like that,
the instance won't be evacuated.

Allow to select which instances to evacuate

---

README.md

Updated the language (grammar) in the Readme.md. The actual information should be the same, just delivered in a more polished format.
This is a squashed replacement for #31.

README wording update

---

README.md

Added a link to the cluster wiki at the bottom of the README.

docs: added link to cluster wiki in README

---

fence/agents/compute/fence_compute.py

Let's scratch my OCD itches here instead of polluting other more meaningful pull requests which I will submit soon ;-)

Fix a couple of typos

---

fence/agents/sbd/fence_sbd.py

sbd command exits with 0 on success but fence functions
should return True in this case

fence_sbd: fix return value of fence functions

---

fence/agents/apc/fence_apc.py

More info at: https://bugzilla.redhat.com/show_bug.cgi?id=1342584

fence_apc: fix for connection timed out issue

---

tests/data/metadata/fence_compute.xml

Regression introduced in 0f170a937bd0944e172004dc30df2fc240d9ca20

Fix travis

---

fence/agents/azure_arm/fence_azure_arm.py
tests/data/metadata/fence_azure_arm.xml

remove getopt for new parameters

---

.gitignore
make/release.mk

Based upon https://github.com/ClusterLabs/libqb/pull/260

build: some cleanups to release.mk

---

.travis.yml
configure.ac
fence/agents/gce/fence_gce.py
tests/data/metadata/fence_gce.xml

First implementation of GCE agent

fence_gce: new agent

---

fence/agents/powerman/fence_powerman.py

Using variable interpreter enables switch to python3.

fence_powerman: use @PYTHON@ for interpreter

---

configure.ac
fence/agents/Makefile.am
fence/agents/heuristics_ping/fence_heuristics_ping.py
fence/agents/kdump/fence_kdump.c
fence/agents/kdump/fence_kdump_send.c
make/agentccheck.mk
make/agentpycheck.mk
make/fencebuild.mk
tests/fence_testing.py

- Updated find and time parameters
- Exclude agents if Python library not present
- Added include to kdump to make it compile (still coredumps though)

build: fixes to support FreeBSD

---

fence/agents/gce/fence_gce.py

Catch any exceptions and write them to the log.
Also generally make the code a bit more pythonic.

fence_gce: Clean up and log errors

---

agents/gce/fence_gce.py

oauth2client is deprecated, replacing it by google-auth

fence_gce: google-auth instead of oauth2client

---

lib/Makefile.am

Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

[build] be more aggressive in cleaning the source tree

---

agents/aliyun/fence_aliyun.py
tests/data/metadata/fence_aliyun.xml

Add Alibaba Cloud fence agent.

Add Aliyun fence agent.

---

agents/aliyun/fence_aliyun.py

100 is the highest number allowed for the PageSize parameter.

fence_aliyun: list instance names and show up to 100 instances

---

agents/vmware_soap/fence_vmware_soap.py

e.g. when stonith kills the process.

fence_vmware_soap: cleanup when receiving SIGTERM

---

agents/compute/fence_compute.py
agents/evacuate/fence_evacuate.py
tests/data/metadata/fence_compute.xml
tests/data/metadata/fence_evacuate.xml

fence_compute/fence_evacuate: domain parameter fixes to avoid

---

agents/openstack/fence_openstack.py

keystoneclient is deprecated in favor of keystoneauth1.

fence_openstack: Migrate from keystoneclient to keystoneauth1

---

agents/hpblade/fence_hpblade.py

Update the 'log_expect' call to the new method definition.

Fix 'log_expect' in fence_hpblade.py

---

agents/redfish/fence_redfish.py
tests/data/metadata/fence_redfish.xml

- Agent works on all fence devices that implement the Redfish API specification
- Agent programatically finds the Systems Resouce URI if it's not provided

Add new fence agent for Redfish

---

agents/scsi/fence_scsi.py
tests/data/metadata/fence_scsi.xml

Added options to be able to be able to set number of retries and sleep between retries.

fence_scsi: watchdog retries support

---

agents/redfish/fence_redfish.py

* Needed for full compliance with Redfish spec.
* May cause errors in some devices if not sent.

fence_redfish: add headers to HTTP methods

---

agents/aliyun/fence_aliyun.py

Add "EcsRamRoleCredential" class from aliyun SDK
https://github.com/ClusterLabs/fence-agents/pull/282 rebased against master.

fence_aliyun: import EcsRamRoleCredential

---

agents/apc_snmp/fence_apc_snmp.py

Tested with Tripplite PDU15NETLX 15.5.4 - SNMP v1, v2c, v3
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

fence_apc_snmp: Add Tripplite WEBCARDLX PDU support

---

agents/mpath/fence_mpath.py
tests/data/metadata/fence_mpath.xml

https://github.com/ClusterLabs/fence-agents/issues/292

fence_mpath: use -n/--plug/port parameter to be able to use pcmk_host_map

---

agents/openstack/fence_openstack.py
tests/data/metadata/fence_openstack.xml

Fixes issues found when testing the patch for fence_mpath: https://github.com/ClusterLabs/fence-agents/pull/298

fence_openstack: fix fail_usage() issue and a couple of other minor issues w/the newly added plug/port parameter

---

agents/ibmz/fence_ibmz.py
doc/COPYRIGHT
fence-agents.spec.in
tests/data/metadata/fence_ibmz.xml

This agent manages IBM z LPARs via the HMC Web Services REST API.

Add fence agent for IBM z LPARs

---

agents/ibmz/fence_ibmz.py

According to its documentation the HMC API should return an
empty array when an LPAR is not found but instead for CPCs in classic
mode it returns a 404 response. This patch changes the
handling of the response to handle the situation accordingly.
Signed-off-by: Paulo de Rezende Pinatti <ppinatti@linux.ibm.com>

fence_ibmz: fix handling of API response when LPAR is not found

---

agents/lpar/fence_lpar.py

When Pacemaker executes `fence_lpar` and the HMC command line is greater
than 80 characters, a parse error causes agent failure. This can happen
with a long user name and/or long managed system name. It happens only
when Pacemaker spawns the `fence_lpar` process; it does not happen when
`fence_lpar` is run from the CLI.
A long command line gets a carriage return ('\r') added at the 80
character mark and wraps back to the beginning of the line with no line
feed ('\n'), overwriting the displayed characters. `fence_lpar`'s regex
matches handle this fine when it's run from the command line.
The problem is that when Pacemaker spawns fence_lpar, **for some
reason** there are backspace characters in the buffer when we hit the
'\r' character. This seems to overwrite some of the `conn.before` …

fence_lpar: Fix parse error from long command line

---

lib/fencing.py.py

To fix issue found in https://github.com/ClusterLabs/fence-agents/issues/358.

fencing: fix power-timeout when using new disable-timeout parameter

---

agents/mpath/fence_mpath.py
agents/scsi/fence_scsi.py

Signed-off-by: Reid Wahl <nrwahl@protonmail.com>

fence_mpath, fence_scsi: Improve logging for failed res/key get

---

.travis.yml
agents/gce/fence_gce.py
configure.ac
tests/data/metadata/fence_gce.xml

Adds the ability to use a service acount for authentiation using --serviceaccount.
Adds additional debug information.

Adds service account authentication to GCE fence agent

---

agents/lpar/fence_lpar.py
tests/data/metadata/fence_lpar.xml

The agent fails with a usage error if this is not present.
Signed-off-by: Reid Wahl <nrwahl@protonmail.com>

fence_lpar: Make --managed a required option

---

agents/redfish/fence_redfish.py
tests/data/metadata/fence_redfish.xml

Sends NMI to fenced node.
Ref:
- http://redfish.dmtf.org/schemas/DSP2046_2020.3.html#redfish.dmtf.org/schemas/v1/ComputerSystem.json|details|ResetType
Resolves: RHBZ#1920947
Signed-off-by: Reid Wahl <nrwahl@protonmail.com>
**Note**: This is a WIP because I don't have the necessary hardware to test this.

fence_redfish: Add diag action

---

agents/Makefile.am
agents/virt/client/Makefile.am
agents/virt/common/Makefile.am
agents/virt/config/Makefile.am
agents/virt/server/Makefile.am
configure.ac

Propagate CFLAGS/AM_CFLAGS and overrides correctly.

Fix clang builds

---

agents/virt/server/Makefile.am
fence-agents.spec.in

Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

virt: fix plugin installation regression on upgrades

---

agents/lindy_pdu/fence_lindypdu.py
tests/data/metadata/fence_lindypdu.xml

New fence agent for Lindy PDU model 32657 (8-16 plugs)

fence_lindypdu: new fence agent

---

agents/kubevirt/fence_kubevirt.py
tests/data/metadata/fence_kubevirt.xml

Signed-off-by: Nir Argaman <nargaman@redhat.com>

fence_kubevirt: new fence agent

---

agents/cyberpower/fence_cyberpower_ssh.py
agents/cyberpower_ssh/fence_cyberpower_ssh.py
fence-agents.spec.in
tests/data/metadata/fence_cyberpower_ssh.xml

This agent was created using fence_apc as a guide. I've tested it on a command line and within oVirt and it behaves correctly for those two cases.

fence_cyberpower_ssh: new fence agent

---

lib/azure_fence.py.py

fix support for Azure Sovereign clouds like China or USGov and MSI support

azure_fence: fix support for sovereign clouds and MSI for new versions of azure libraries

---

agents/amt_ws/fence_amt_ws.py

Thanks to Seth Arnold for reporting it in https://github.com/ClusterLabs/fence-agents/issues/434.

fence_amt_ws: fix "or" causing dead code

---

agents/raritan_px3/fence_raritan_px3.py
doc/COPYRIGHT
tests/data/metadata/fence_raritan_px3.xml

Tested on model PX3-5466V with firmware version: 3.6.0.5

fence_raritan_px3: new fence agent

---

agents/vmware_soap/fence_vmware_soap.py

fence_vmware_soap: Use --login-timeout option

---

agents/aliyun/fence_aliyun.py

1. Optimize log output
2. Optimize region and ram role check logic

fence_aliyun: Optimize log output

---

agents/lpar/fence_lpar.py

When the managed system has NovaLink installed it is still possible to
manage the system with HMC with correct chcomgmgt setting but profiles
are not supported.
@watologo1

fence_lpar: Support comanaged LPARs

---

agents/openstack/fence_openstack.py
tests/data/metadata/fence_openstack.xml

- hardcoded clouds.yaml paths to work like the openstack cli client
(used by the resource agents)

fence_openstack: fix issues with new clouds.yaml/openrc parameters

---

agents/gce/fence_gce.py
tests/data/metadata/fence_gce.xml

This allows the agent to be more flexible to the users needs and improves reliability.

fence_gce: Add timeouts and failure options

---

agents/cisco_ucs/fence_cisco_ucs.py
agents/docker/fence_docker.py
agents/ibmz/fence_ibmz.py
agents/pve/fence_pve.py
agents/rhevm/fence_rhevm.py
agents/skalar/fence_skalar.py
agents/vmware_rest/fence_vmware_rest.py
agents/vmware_soap/fence_vmware_soap.py
agents/vmware_vcloud/fence_vmware_vcloud.py
agents/zvm/fence_zvmip.py
lib/fencing.py.py
tests/data/metadata/fence_docker.xml
tests/data/metadata/fence_pve.xml

THIS MIGHT BREAK SETUPS USING fence_docker or fence_pve!

all agents: unify ssl parameters to avoid having to use --ssl when using --ssl-secure/--ssl-insecure for some agents

---

agents/ecloud/fence_ecloud.py
doc/COPYRIGHT
fence-agents.spec.in
tests/data/metadata/fence_ecloud.xml

Hello.
This adds a new fence agent for use with ANS Group's eCloud platform.

fence_ecloud: new fence agent

---

agents/scsi/fence_scsi.py

Reverts ClusterLabs/fence-agents#501

Revert "fence_scsi: fail monitor action when it's unable to change state of device"

---

agents/virt/man/fence_virt.conf.5

https://github.com/ClusterLabs/fence-agents/issues/506

fence_virtd: add link and non-user socket example to man page

---

agents/aliyun/fence_aliyun.py
tests/data/metadata/fence_aliyun.xml

In order to solve the list-action list too many nodes, add ‘--filter’ parameter

fence_aliyun: support filter for list-action

---

agents/ibm_powervs/fence_ibm_powervs.py
tests/data/metadata/fence_ibm_powervs.xml

- improved performance using less power-iaas.cloud.ibm.com API calls
- add support for reboot_cycle, method to fence (onoff|cycle) (Default: onoff)

fence_ibm_powervs: improved performance

---

agents/ipmilan/fence_ipmilan.py
tests/data/metadata/fence_idrac.xml
tests/data/metadata/fence_ilo3.xml
tests/data/metadata/fence_ilo4.xml
tests/data/metadata/fence_ilo5.xml
tests/data/metadata/fence_imm.xml
tests/data/metadata/fence_ipmilan.xml
tests/data/metadata/fence_ipmilanplus.xml

fence_ipmilan: fix typo in description

---

doc/fa-dev-guide.md

- add General git section
- add reboot_cycle() section
- improve fail()/error code description

fa-dev-guide: updates

---

agents/scsi/fence_scsi.py

Problem:
When a device is powered off (preempted), fence_scsi agent assumes that the client has a registration to the device and sends a preempt-and-abort request on the key held by the other device. This fails due to reservation conflict if the host registration has a conflicting ISID. (Another manifestation of problem https://github.com/ClusterLabs/fence-agents/pull/529)
Impact:
If the local host is unable to preempt any other hosts because a matching registration with local host is not found, then the local host won't be able to start the resources.
Proposed Fix:
To fix this, the agent needs to register with the host key before it tries a preempt request.

fence_scsi: fix registration handling in device 'off' workflows

---

agents/ovm/fence_ovm.py
doc/COPYRIGHT
fence-agents.spec.in
tests/data/metadata/fence_ovm.xml

Hello.
Adds a fencing agent for virtual machines managed by Oracle VM.
fence-ovm uses Oracle VM Manager REST API.
https://docs.oracle.com/en/virtualization/oracle-vm/3.4/developer/vmapi-rest.html
Tested with Oracle VM Manager 3.4 on Oracle Linux Server 7.9.

fence_ovm: new fence agent for Oracle VM

---

agents/alom/fence_alom.py
agents/amt/fence_amt.py
agents/apc/fence_apc.py
agents/azure_arm/fence_azure_arm.py
agents/cdu/fence_cdu.py
agents/cisco_ucs/fence_cisco_ucs.py
agents/gce/fence_gce.py
agents/ilo/fence_ilo.py
agents/ilo_mp/fence_ilo_mp.py
agents/ilo_ssh/fence_ilo_ssh.py
agents/ipmilan/fence_ipmilan.py
agents/ironic/fence_ironic.py
agents/lpar/fence_lpar.py
agents/netio/fence_netio.py
agents/raritan/fence_raritan.py
agents/rhevm/fence_rhevm.py
agents/rsa/fence_rsa.py
agents/wti/fence_wti.py
lib/azure_fence.py.py
lib/fencing.py.py
lib/fencing_snmp.py.py

Fixes https://github.com/ClusterLabs/fence-agents/issues/570

lib/all agents: use r"" for all regular expressions to avoid SyntaxWarning errors

---

agents/aws/fence_aws.py

Thanks @wenningerk for the suggestion.

fence_aws: log error if unknown state returned

---

agents/raritan_px3/fence_raritan_px3.py
lib/fence2man.xsl

python3: SyntaxWarning: invalid escape sequence '\['
troff: error: invalid base glyph 'My' in composite glyph name

fence_raritan_px3: fix syntax warnings

---

lib/azure_fence.py.py

Fix for Managed service identity azure authentication 
The pr fixes #603

azure_fence.py: fix managed identity authentication
